language: cpp

install:
 - wget http://bitbucket.org/eigen/eigen/get/3.2.6.tar.gz
 - tar zxvf 3.2.6.tar.gz 
 - mv eigen-eigen-c58038c56923 eigen3

script:
 - mkdir build
 - cd build
 - cmake ..
 - make -j2

